### ISSUE TITLE
No BoM?

### ISSUE THREAD

**Issue by smartroad** [reprappro/Mendel#1]
Hay guys!

Maybe I am not looking in the right place but I can't find the bill of materials for this version.

**Comment by reprappro** [comment]
Hi 

The BoM is deliberately embedded in the assembly instructions.  If you look, for example, here:

http://reprappro.com/wiki/index.php/RepRapPro_Tricolour_y_axis_assembly

You will see that each step has a BoM associated with it for what is needed at that step.  This way, when we update things, the BoM never gets out of sync.

Best wishes

Adrian
