### ISSUE TITLE
Openscad directory does not clearly indicate that some parts are now .STEP and .SLDPRT files elsewhere

### ISSUE THREAD

**Issue by o-jasper** [reprappro/Mendel#2]
I, for one was confused :) Probably better to add some information on what is what?

Reading the wikipedia page, maybe solidworks is better. Openscad([implictcad](http://implicitcad.org/)) work on a higher level than specific design. Basically making a specific design is 'write what you get' openscad is more like 'program what you want', and what we kindah want is 'write what you want'.. (edit: not having used solidworks i dont know if it achieves anything like it)(but aside...)

**Comment by reprappro** [comment]
All required 3D models are available in the Print-mendel folder. Openscad is used for simple parts and is free and open source.
Solidworks is neither free nor open source, but makes it much easier to design parts with complex shapes.

If you wish to discuss the merit of various CAD software, the RepRap forums would be a more suitable place http://forums.reprap.org/search.php?0,search=solidworks,author=,page=1,match_type=ALL,match_dates=30,match_forum=ALL,match_threads=0
